# CodeRabbit Configuration for BidDeed.AI
# https://docs.coderabbit.ai/configuration

language: en-US

reviews:
  # Enable automatic PR reviews
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop
  
  # Review depth settings
  profile: assertive
  
  # Focus areas for agentic AI codebase
  path_instructions:
    - path: "src/agents/**"
      instructions: |
        Focus on agent communication patterns, state management, and error handling.
        Check for race conditions in multi-agent workflows.
        Validate proper cleanup of agent resources.
    
    - path: "src/scrapers/**"
      instructions: |
        Verify anti-detection measures are in place.
        Check for proper error handling and retry logic.
        Ensure rate limiting compliance.
    
    - path: "src/pipeline/**"
      instructions: |
        Validate stage transitions and checkpoint handling.
        Check for proper circuit breaker patterns.
        Review data validation at stage boundaries.
    
    - path: "**/*.sql"
      instructions: |
        Check for SQL injection vulnerabilities.
        Verify proper indexing for query performance.
        Review RLS policies for data security.

  # High-priority checks
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  
  # Request changes for critical issues
  request_changes_workflow: true

chat:
  auto_reply: true

# Ignore patterns
path_filters:
  - "!**/*.min.js"
  - "!**/node_modules/**"
  - "!**/*.lock"
  - "!**/dist/**"
  - "!**/__pycache__/**"
  - "!**/.git/**"

# Enable learning from feedback
early_access: true
